const {test}=require('node:test');
const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');
const root=path.resolve(__dirname,'..');
test('Reglas, tácticas y motor: 60 comprobaciones',()=>{
 const ctx=vm.createContext({console});
 for(const file of ['vendor/chess.js','vendor/garbo.js','catalog.js','tactics.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),ctx,{filename:file});
 const checks=vm.runInContext("\nconst results=[];function check(name,b){if(!b)throw Error(name);results.push(name);}\nconst c=new Chess();\nfunction perft(c,d){if(!d)return 1;let n=0;for(const m of c.moves({verbose:true})){c.move(m);n+=perft(c,d-1);c.undo();}return n;}\ncheck('Perft inicial: 20, 400, 8902',perft(c,1)===20&&perft(c,2)===400&&perft(c,3)===8902);\ncheck('Catálogo completo: 81 fichas, 75 Lichess + 6 propias',CATALOG.length===81&&new Set(CATALOG.map(t=>t.id)).size===81);\ncheck('81 controles reconocidos',ACTIVE_THEMES.length===81&&ACTIVE_THEMES.every(id=>CATALOG.some(t=>t.id===id)));\nfor(const f of FIXTURES)check('Ejemplo: '+f.name,analyzeChess(new Chess(f.fen),{mateIn1:true}).alerts.some(a=>a.type===f.expected));\nconst falseDiscovery=new Chess('r5k1/8/8/8/8/8/R7/R5K1 w - - 0 1');\nconst discovered=analyzeChess(falseDiscovery).alerts.filter(a=>a.type==='discoveredAttack');\ncheck('No anuncia descubierta contra pieza ya capturada',discovered.every(a=>a.move.to!=='a8'));\nfor(const a of discovered){const copy=new Chess(falseDiscovery.fen());copy.move(a.move);check('Objetivo descubierto sigue siendo rival',copy.get(a.squares[2]).color!==copy.get(a.squares[1]).color);}\nconst pinned=new Chess(FIXTURES[0].fen);check('Clavada absoluta impide mover caballo',pinned.moves({square:'e7'}).length===0);\nconst castle=new Chess('r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1');check('Enroques legales',castle.moves().includes('O-O')&&castle.moves().includes('O-O-O'));\nconst noCastle=new Chess('r3kr1r/8/8/8/8/8/8/R3K2R w KQ - 0 1');check('No enroca atravesando jaque',!noCastle.moves().includes('O-O'));\nconst ep=new Chess();['e4','a6','e5','d5'].forEach(m=>ep.move(m));check('Captura al paso disponible',analyzeChess(ep).alerts.some(a=>a.type==='enPassant'));ep.move('Nf3');ep.move('a5');check('Captura al paso caduca',!ep.moves({verbose:true}).some(m=>m.flags.includes('e')));\nconst promo=new Chess(FIXTURES[4].fen);check('Cuatro coronaciones',promo.moves({verbose:true}).filter(m=>m.promotion).length===4);\nconst mate=new Chess();['f3','e5','g4','Qh4#'].forEach(m=>mate.move(m));check('Mate',mate.in_checkmate());check('Ahogado',new Chess('7k/5Q2/6K1/8/8/8/8/8 b - - 0 1').in_stalemate());\nconst repeat=new Chess();['Nf3','Nf6','Ng1','Ng8','Nf3','Nf6','Ng1','Ng8'].forEach(m=>repeat.move(m));check('Triple repetición',repeat.in_threefold_repetition());\nconst engineGame=new Chess();let plies=0;while(plies<40&&!engineGame.game_over()){const result=GARBO.choose(engineGame.fen(),70,3);check('Motor legal '+(plies+1),Boolean(result&&engineGame.move({from:result.uci.slice(0,2),to:result.uci.slice(2,4),promotion:result.uci[4]||'q'})));plies++;}\nresults;\n",ctx,{timeout:30000});
 console.log(checks.length+' comprobaciones de reglas, tácticas y motor superadas');
});
